name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    - name: Run shellcheck
      run: shellcheck install.sh gifify.sh
    - name: Verify version match
      run: |
        version=$(cat VERSION)
        script_version=$(grep -oE 'GIFIFY_VERSION="([^"]+)"' gifify.sh | cut -d'"' -f2)
        if [ "$version" != "$script_version" ]; then
          echo "VERSION mismatch: $version vs $script_version" >&2
          exit 1
        fi

